# This is a basic workflow to test Apex Tank Candidate

name: Test Candidate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request_target:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Navigate to checked out folder
        run: cd $GITHUB_WORKSPACE

     # setup sfdx using action 
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}

      # Check deploy with single test run
      - name: Test Apex Tank Candidate
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          changes=$(curl -s -X GET -G $URL | jq -r '.[] | .filename' | grep ".cls")
          changes=$(echo $changes | tr ' ' ,)
          echo "This is changes: $changes"
          sfdx force:source:deploy -c -l RunSpecifiedTests -r CandidateTest -p "$changes" --verbose
